#!/usr/bin/env sh
#YABAI STUFF

# needed for macOS big sur:
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# bsp or float (default: bsp)
yabai -m config layout bsp
yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     0
yabai -m config external_bar all:0:26
yabai -m config split_ratio 0.5

yabai -m config window_shadow float

yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# borders
yabai -m config window_border off
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xff98c379
yabai -m config normal_window_border_color 0x00FFFFFF

# opacity
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0
yabai -m config normal_window_opacity 0.6
yabai -m config active_window_opacity 1

# insertion color:
yabai -m config insert_feedback_color 0xFFD75F5F

# custom space names
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 9 --label nine

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=normal manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=normal manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=normal manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=normal manage=off
# yabai -m rule --add app="^Keka$" sticky=on layer=normal manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=normal manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=normal manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=normal manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=normal manage=off
yabai -m rule --add app="^SonicWall" sticky=on layer=normal manage=off
yabai -m rule --add app="^1Password 7$" sticky=on layer=normal manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^console$" manage=off
# yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^NordVPN IKE$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Synergy" manage=off
yabai -m rule --add app="^CJLauncher" manage=off


echo "yabai configuration loaded.."

#END
